### ISSUE TITLE
Invalid Device Function in Example

### ISSUE THREAD

**Issue by eric-qian-d** [mit-han-lab/torchsparse#79]
I'm running into the following issue when I run `example.py`

<img width="1586" alt="Screen Shot 2021-06-13 at 9 23 07 PM" src="https://user-images.githubusercontent.com/30250617/121832254-467e3d00-cc8f-11eb-82f6-b3d0bcd5cb1f.png">

I believe the hardware and software should all be compatible

<img width="1084" alt="Screen Shot 2021-06-13 at 9 35 53 PM" src="https://user-images.githubusercontent.com/30250617/121832473-b987b380-cc8f-11eb-858a-d2739cd593f1.png">
<img width="759" alt="Screen Shot 2021-06-13 at 9 36 32 PM" src="https://user-images.githubusercontent.com/30250617/121832482-be4c6780-cc8f-11eb-950e-c828f9e8413e.png">
<img width="722" alt="Screen Shot 2021-06-13 at 9 38 31 PM" src="https://user-images.githubusercontent.com/30250617/121832485-c1dfee80-cc8f-11eb-9d67-39b24b7ef19d.png">

**Comment by kentangSJTU** [comment]
Hi Eric,

I actually tried torchsparse on GTX1080Ti which also has `compute_61` and `sm_61` and did not run into this error. Would you mind cloning this repo and run
```bash
python setup.py install
```
again to check whether the error still exists? Thanks!

Best,
Haotian

**Comment by eric-qian-d** [comment]
Hi Haotian,

Thank you for the quick response! I ran the command and I am still getting the same error with the new installation. I tried running `example.py` on a machine with RTX2080Ti which showed the same error. 

<img width="1677" alt="Screen Shot 2021-06-13 at 10 56 30 PM" src="https://user-images.githubusercontent.com/30250617/121837262-c362e400-cc9a-11eb-9b3d-0ca4aba9d389.png">

Best,
Eric

**Comment by kentangSJTU** [comment]
Hi Eric,

Thanks for the information. RTX2080Ti can also run torchsparse, so I guess this is still a problem related to CUDA version.

I also searched for this error in other repos, and I found a typical response from detectron2 [here](https://github.com/facebookresearch/detectron2/issues/62#issuecomment-542447753). I'm not sure whether you installed conda with 
```bash
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
```

You may check that by running
```python
import torch.__config__
print(torch.__config__.show())
```
in Python. If the `CUDA Runtime` entry is not 10.2, I believe there's some problem.


Best,
Haotian

**Comment by CCInc** [comment]
It might be related to pytorch 1.6. I've only tested on 1.7 and 1.8+. Can you try in a new environment with one of those versions?

**Comment by kentangSJTU** [comment]
Thanks @CCInc for the comment. I actually tried PyTorch 1.6 on GTX1080Ti and did not encounter similar bugs, but I'm not sure whether it is the same case for TitanXp.

**Comment by eric-qian-d** [comment]
My previous installation looks like

```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
 ```

If I do a fresh install, my installation (python-3.8.10, pytorch-1.8.1) looks like

```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON
  ```

With the new installation, setting up `torchsparse` actually fails with 

```
[1/23] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/build/temp.linux-x86_64-3.8/torchsparse/src/convolution/convolution.o.d -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/TH -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/include/python3.8 -c -c /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/torchsparse/src/convolution/convolution.cu -o /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/build/temp.linux-x86_64-3.8/torchsparse/src/convolution/convolution.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=torchsparse_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/build/temp.linux-x86_64-3.8/torchsparse/src/convolution/convolution.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/build/temp.linux-x86_64-3.8/torchsparse/src/convolution/convolution.o.d -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/TH -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/vision/billf/intrinsic/neural-render/ericqian/software/miniconda3/envs/torchsparse/include/python3.8 -c -c /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/torchsparse/src/convolution/convolution.cu -o /data/vision/billf/scratch/ericqian/neural-render/code/torchsparse/build/temp.linux-x86_64-3.8/torchsparse/src/convolution/convolution.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=torchsparse_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
```

A similar issue was posed also in detectron2 saying that this nvcc doesn't match cuda10.2: https://github.com/facebookresearch/detectron2/issues/2909

When I run `nvcc --version`, I get
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by CCInc** [comment]
It's definitely strange. Is it possible you have multiple versions of nvcc installed? Please try:

`/usr/local/cuda/bin/nvcc --version` 

and let me know if the output is the same.  It might be pulling a different version of nvcc than the one that's on your path.

**Comment by eric-qian-d** [comment]
That turned out to be the issue! After exporting the correct `LD_LIBRARY_PATH` and `CUDA_HOME`, everything now works. Thank you both for your help!

**Comment by CCInc** [comment]
Great! Glad to hear it!
